"""
generate_document_text_source.py

SAS821S · T18 - Insurance Claims Fraud, Identity Abuse and Data-Leakage Analytics
Generates the synthetic "Document Metadata and OCR/Text Data" source described
in the Project Charter (Section 6):

    Document ID, Claimant ID, Upload Time, File Type, File Size,
    OCR Text, Document Similarity Indicators

Design notes
------------
- Fully synthetic: no real customer data is used or required (Faker only).
- 220 records generated by default (charter minimum is 200+).
- ~18% of records are deliberately built as near-duplicate / templated OCR
  text tied to a shared "duplicate_group_id", so the text-mining/NLP
  component (Section 10 of the Implementation Plan) has real similarity
  patterns to detect, rather than fabricating results afterwards.
- A minority of records are flagged "high_similarity" so Document Similarity
  Indicators is a genuine, non-trivial computed field (via difflib), not a
  random label.

Run:
    python3 generate_document_text_source.py
Output:
    02_data/raw/document_metadata_ocr_text.csv
"""

import csv
import os
import random
import difflib
from datetime import datetime, timedelta

from faker import Faker

fake = Faker()
Faker.seed(42)
random.seed(42)

N_RECORDS = 220
N_CLAIMANTS = 140          # some claimants submit more than one document
OUTPUT_DIR = "02_data/raw"
OUTPUT_FILE = os.path.join(OUTPUT_DIR, "document_metadata_ocr_text.csv")

FILE_TYPES = ["PDF", "JPG", "PNG", "DOCX"]

# Reusable OCR "document templates" -----------------------------------------
# Each template has placeholder slots. Multiple documents drawn from the same
# template (with only claimant/date/amount swapped) simulate the
# "repeated content across claims" fraud indicator described in the charter's
# problem statement.

TEMPLATES = [
    ("claim_form",
     "INSURANCE CLAIM FORM. Claimant: {name}. Policy Number: {policy}. "
     "Date of Incident: {date}. Description: Vehicle damage sustained in a "
     "collision on {road}. Estimated repair cost: N$ {amount}. "
     "Signed: {name}."),
    ("id_document",
     "NATIONAL IDENTITY DOCUMENT. Full Name: {name}. ID Number: {idnum}. "
     "Date of Birth: {dob}. Nationality: Namibian. Issued by Ministry of "
     "Home Affairs. Address updated on {date}."),
    ("kyc_update",
     "KYC UPDATE FORM. Customer: {name}. Previous Address: {old_addr}. "
     "New Address: {new_addr}. Reason for change: relocation. Verified by "
     "staff member on {date}."),
    ("medical_report",
     "MEDICAL ASSESSMENT REPORT. Patient: {name}. Injury sustained during "
     "incident on {date}. Attending physician: Dr. {doctor}. Recommended "
     "treatment plan attached. Estimated cost: N$ {amount}."),
    ("bank_statement",
     "BANK STATEMENT EXTRACT. Account Holder: {name}. Statement period: "
     "{date} to {date2}. Closing balance: N$ {amount}. Branch: {branch}."),
    ("investigation_note",
     "INVESTIGATION NOTE. Case relates to claimant {name}. Flagged for "
     "review due to unusual document upload pattern following identity "
     "change on {date}. Staff override recorded by {staff}."),
]


def random_date(start_days_back=365, end_days_back=0):
    start = datetime.now() - timedelta(days=start_days_back)
    end = datetime.now() - timedelta(days=end_days_back)
    delta = end - start
    return start + timedelta(days=random.randint(0, max(delta.days, 1)))


FILLER_SENTENCES = [
    "Handled by branch office during standard working hours.",
    "Customer contacted via telephone for confirmation.",
    "Supporting documents received by email attachment.",
    "Case referenced against prior claim history for context.",
    "Client requested expedited processing due to urgency.",
    "Form completed in person at the regional service counter.",
    "Additional photographic evidence submitted separately.",
    "No prior claims recorded against this policy in the last 3 years.",
    "Witness statement attached as a separate document.",
    "Follow-up scheduled with the claims handler within 5 working days.",
]


def build_ocr_text(template_key, template_str, name, force_boilerplate_only=False):
    """
    Fill a template with fake but plausible field values, then append 1-3
    randomly chosen filler sentences so that two DIFFERENT, unrelated
    documents of the same type do not read as near-identical purely because
    they share the same boilerplate skeleton. Only true duplicate-group
    documents skip this (force_boilerplate_only=True) so they remain
    genuinely near-identical, which is the pattern we want detectable.
    """
    base = template_str.format(
        name=name,
        policy=f"POL-{random.randint(100000, 999999)}",
        date=random_date().strftime("%Y-%m-%d"),
        date2=random_date().strftime("%Y-%m-%d"),
        road=fake.street_name(),
        amount=f"{random.randint(500, 85000):,}",
        idnum=fake.ssn(),
        dob=fake.date_of_birth(minimum_age=18, maximum_age=75).isoformat(),
        old_addr=fake.address().replace("\n", ", "),
        new_addr=fake.address().replace("\n", ", "),
        doctor=fake.last_name(),
        branch=fake.city(),
        staff=fake.name(),
    )
    if force_boilerplate_only:
        return base
    n_filler = random.randint(1, 3)
    filler = " ".join(random.sample(FILLER_SENTENCES, n_filler))
    return f"{base} {filler}"


def similarity_score(a, b):
    return round(difflib.SequenceMatcher(None, a, b).ratio(), 3)


def main():
    os.makedirs(OUTPUT_DIR, exist_ok=True)

    claimant_ids = [f"CLM-{str(i).zfill(5)}" for i in range(1, N_CLAIMANTS + 1)]
    claimant_names = {cid: fake.name() for cid in claimant_ids}

    records = []
    duplicate_group_counter = 0

    # --- Step 1: build a pool of "duplicate group" records first -----------
    n_duplicate_records = int(N_RECORDS * 0.18)
    n_unique_records = N_RECORDS - n_duplicate_records

    doc_counter = 1

    # Duplicate / near-duplicate groups: same template reused for a cluster
    # of documents (simulating copy-pasted or reused fraudulent content).
    remaining_dupes = n_duplicate_records
    while remaining_dupes > 0:
        group_size = min(random.randint(2, 4), remaining_dupes)
        duplicate_group_counter += 1
        group_id = f"DUPGRP-{duplicate_group_counter:03d}"
        key, template = random.choice(TEMPLATES)
        base_name = random.choice(list(claimant_names.values()))
        base_text = build_ocr_text(key, template, base_name, force_boilerplate_only=True)

        for _ in range(group_size):
            claimant_id = random.choice(claimant_ids)
            # near-duplicate: reuse base_text verbatim, or regenerate from the
            # same template/name (still boilerplate-only -> stays near-identical)
            variant_text = base_text
            if random.random() < 0.5:
                variant_text = build_ocr_text(key, template, base_name, force_boilerplate_only=True)
            records.append({
                "document_id": f"DOC-{doc_counter:05d}",
                "claimant_id": claimant_id,
                "upload_time": random_date().strftime("%Y-%m-%d %H:%M:%S"),
                "file_type": random.choice(FILE_TYPES),
                "file_size_kb": random.randint(80, 4500),
                "ocr_text": variant_text,
                "duplicate_group_id": group_id,
                "document_type": key,
            })
            doc_counter += 1
        remaining_dupes -= group_size

    # Unique, non-duplicated documents
    for _ in range(n_unique_records):
        claimant_id = random.choice(claimant_ids)
        name = claimant_names[claimant_id]
        key, template = random.choice(TEMPLATES)
        text = build_ocr_text(key, template, name)
        records.append({
            "document_id": f"DOC-{doc_counter:05d}",
            "claimant_id": claimant_id,
            "upload_time": random_date().strftime("%Y-%m-%d %H:%M:%S"),
            "file_type": random.choice(FILE_TYPES),
            "file_size_kb": random.randint(80, 4500),
            "ocr_text": text,
            "duplicate_group_id": "",
            "document_type": key,
        })
        doc_counter += 1

    random.shuffle(records)

    # --- Step 2: compute a real Document Similarity Indicator per record ---
    # Compare each document's OCR text against the others in its duplicate
    # group (if any); otherwise against a small random sample, and keep the
    # single highest similarity score found. This makes the "indicator" a
    # genuine computed value rather than a placeholder.
    by_group = {}
    by_type = {}
    for r in records:
        by_group.setdefault(r["duplicate_group_id"], []).append(r)
        by_type.setdefault(r["document_type"], []).append(r)

    for r in records:
        group = r["duplicate_group_id"]
        if group:
            peers = [x["ocr_text"] for x in by_group[group] if x is not r]
        else:
            # Compare only against other documents of the SAME type, since
            # comparing across unrelated templates (e.g. medical report vs.
            # bank statement) is meaningless and would just read as LOW.
            same_type_peers = [x["ocr_text"] for x in by_type[r["document_type"]]
                                if x is not r]
            peers = random.sample(same_type_peers, k=min(6, len(same_type_peers)))

        best = max((similarity_score(r["ocr_text"], p) for p in peers), default=0.0)
        r["document_similarity_score"] = best
        # Thresholds calibrated so only genuine near-duplicates (shared
        # boilerplate WITHOUT the randomised filler sentences) score HIGH;
        # ordinary same-type documents with filler text land in LOW/MEDIUM.
        r["document_similarity_flag"] = "HIGH" if best >= 0.90 else (
            "MEDIUM" if best >= 0.70 else "LOW")

    # --- Step 3: write CSV ---------------------------------------------------
    fieldnames = [
        "document_id", "claimant_id", "upload_time", "file_type",
        "file_size_kb", "document_type", "ocr_text",
        "duplicate_group_id", "document_similarity_score",
        "document_similarity_flag",
    ]

    with open(OUTPUT_FILE, "w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        for r in records:
            writer.writerow(r)

    print(f"Wrote {len(records)} records to {OUTPUT_FILE}")
    print(f"  - {n_duplicate_records} in duplicate/near-duplicate groups "
          f"across {duplicate_group_counter} groups")
    print(f"  - {n_unique_records} unique documents")
    high = sum(1 for r in records if r["document_similarity_flag"] == "HIGH")
    print(f"  - {high} records flagged HIGH similarity")


if __name__ == "__main__":
    main()
